[features]
seeds = false
skip-lint = false

[programs.localnet]
universal_nft = "89BWBddtdbMriDFjotkPyzDvcehdJaZMvPYU1LifVjRc"

[programs.devnet]
universal_nft = "89BWBddtdbMriDFjotkPyzDvcehdJaZMvPYU1LifVjRc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
